"""Custom types for the ENGIE Belgium integration."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from collections.abc import Callable

    from homeassistant.config_entries import ConfigEntry
    from homeassistant.helpers.update_coordinator import DataUpdateCoordinator

    from .api import EngieBeApiClient
    from .coordinator import (
        EngieBeDataUpdateCoordinator,
        EngieBeEpexCoordinator,
        EngieBeEpexQuarterHourCoordinator,
    )
    from .store import EngieBeHappyHoursStore, EngieBePeaksStore


def unwrap_dict_payload(
    coordinator: DataUpdateCoordinator[Any],
    key: str,
) -> dict[str, Any] | None:
    """Return the inner ``data`` dict from a coordinator wrapper, or ``None``."""
    if not isinstance(coordinator.data, dict):
        return None
    wrapper = coordinator.data.get(key)
    if not isinstance(wrapper, dict):
        return None
    payload = wrapper.get("data")
    return payload if isinstance(payload, dict) else None


type EngieBeConfigEntry = ConfigEntry[EngieBeData]


@dataclass(slots=True, frozen=True)
class EpexSlot:
    """Single EPEX day-ahead price slot (Brussels-aware, value in EUR/kWh)."""

    start: datetime
    end: datetime
    value_eur_per_kwh: float


@dataclass(slots=True, frozen=True)
class EpexPayload:
    """Latest known EPEX day-ahead slate plus its publication metadata."""

    slots: tuple[EpexSlot, ...]
    publication_time: datetime | None
    market_date: str | None
    slot_duration: timedelta = timedelta(minutes=60)


@dataclass(frozen=False)
class FeatureFlagState:
    """
    Per-subentry feature-flag snapshot.

    ``None`` until first observed, then True/False. Fail-open: an absent
    endpoint reads as False, never as unknown-but-on.
    """

    happy_hour_enrolled: bool | None = None
    solar: bool | None = None
    tou_active: bool | None = None


@dataclass
class EngieBeSubentryData:
    """
    Per-subentry runtime state (one per active business agreement).

    ``is_dynamic_override`` comes from the energy-contracts endpoint and takes
    precedence over the payload-shape heuristic when not None, so a transient
    prices outage never flips the account back to fixed.

    ``happy_hours_store`` records every observed window because the API only
    returns the next upcoming one under ``tomorrow``. Allocated up front so
    later enrolment can record immediately.
    """

    coordinator: EngieBeDataUpdateCoordinator
    service_points: dict[str, str] = field(default_factory=dict)
    peaks_store: EngieBePeaksStore | None = field(default=None)
    happy_hours_store: EngieBeHappyHoursStore | None = field(default=None)
    is_dynamic_override: bool | None = field(default=None)
    energy_contracts_payload: dict[str, Any] | None = field(default=None)
    feature_flags: FeatureFlagState = field(default_factory=FeatureFlagState)


@dataclass
class EngieBeData:
    """
    Parent-entry runtime data.

    Shared client and EPEX coordinator plus per-subentry state.

    ``reload_pending`` is a one-shot debounce so simultaneous Happy Hours
    enrolment flips across subentries collapse to a single ``async_reload``.

    ``pending_subentry_target`` collapses a multi-pick add into one reload:
    the picker sets it to the final expected BAN set before adding, and
    ``async_reload_entry`` suppresses reloads until that set is present, then
    reloads once and clears the gate. Keyed by BAN (``unique_id``) because
    subentry ids are generated by the framework's finish path and not known
    up front. ``None`` means no multi-add is in progress.
    """

    client: EngieBeApiClient
    epex_coordinator: EngieBeEpexCoordinator
    epex_qh_coordinator: EngieBeEpexQuarterHourCoordinator | None = None
    subentry_data: dict[str, EngieBeSubentryData] = field(default_factory=dict)
    authenticated: bool = field(default=False)
    last_options: dict[str, Any] = field(default_factory=dict)
    last_subentry_ids: set[str] = field(default_factory=set)
    reload_pending: bool = field(default=False)
    pending_subentry_target: set[str] | None = field(default=None)
    cancel_token_refresh: Callable[[], None] | None = field(default=None)
