import_history:
  target: {}
  fields:
    energy_type:
      required: false
      default:
        - "consumption"
        - "injection"
        - "gas"
      selector:
        select:
          multiple: true
          translation_key: energy_type
          options:
            - "consumption"
            - "injection"
            - "gas"
    include_costs:
      required: false
      default: false
      selector:
        boolean:
    start_date:
      required: false
      example: "2024-01-01"
      selector:
        date:
    end_date:
      required: false
      example: "2024-06-30"
      selector:
        date:

clear_import_history:
  target: {}
  fields:
    energy_type:
      required: false
      default:
        - "consumption"
        - "injection"
        - "gas"
      selector:
        select:
          multiple: true
          translation_key: energy_type
          options:
            - "consumption"
            - "injection"
            - "gas"
    include_costs:
      required: false
      default: false
      selector:
        boolean:
